name       : celtic-magic-button
version    : 1.1.2
release    : 1
source     :
    - https://github.com/tomocafe/celtic-magic-button/archive/v1.1.2.tar.gz : ae5c613c8fb6380a18cdc170edef49d8c87b9c93deee26477b44aea05a7909a9
license    : CC0-1.0
component  : desktop.budgie
summary    : Budgie panel shutdown button
description: |
    A simple button for the Budgie panel to shut down your computer. The icon used is a Celtic knot, a nod to the official answer to the question, How does Solus shut down so fast?
builddeps  :
    - pkgconfig(budgie-1.0)
    - vala
setup      : |
    %meson_configure -Dpost_install=false
build      : |
    %ninja_build
install    : |
    %ninja_install

